name: shellcheck

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run Static analysis
      run: |
        shellcheck install.sh mdlm.sh
