name: unit-tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  bats:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install BATS
      run: |
        apt-get install bats

    - name: Execute unit tests
      run: |
        bats test/

